version: "3"

services:
  nest:
    build: .
    volumes:
    - ./:/usr/src/app
    ports:
    - "3000:3000"
    networks:
    - api
    depends_on:
    - mongo
  mongo:
    image: mongo:4.2
    ports:
    - "27017:27017"
    networks:
    - api
    environment:
    - MONGO_INITDB_DATABASE= bulkdb

networks:
  api:
    driver: bridge