version: "3"

services:
  nest:
    build: .
    volumes:
    - ./:/usr/src/app
    ports:
    - "3000:3000"
    networks:
    - api
    depends_on:
    - mongo
    - sqldb
  mongo:
    image: mongo:4.2
    ports:
    - "27017:27017"
    networks:
    - api
    environment:
    - MONGO_INITDB_DATABASE= bulkdb
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  sqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'sqldb'
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
    - api
networks:
  api:
    driver: bridge